"""Seed data generator for 200+ origami projects."""
import random

# Step templates by category and skill - ALL KID-FRIENDLY LANGUAGE
def _animal_steps(title, skill):
    if skill == "beginner":
        return [
            {"step_number": 1, "title": "Get Your Paper Ready", "instruction": f"Grab a square piece of colored paper for your {title}. Put it flat on the table like a diamond shape.", "tip": "Pick a fun color that matches your animal!"},
            {"step_number": 2, "title": "Fold in Half", "instruction": "Fold one corner all the way over to the opposite corner to make a triangle. Press down hard on the fold line.", "tip": None},
            {"step_number": 3, "title": "Make the Body", "instruction": f"Fold the triangle to make it look like the body of your {title}. Keep the long flat side at the top.", "tip": "Nice and neat folds make it look the best!"},
            {"step_number": 4, "title": "Add the Fun Parts", "instruction": f"Make little folds to create the ears, nose, or other parts that make your {title} look real.", "tip": None},
            {"step_number": 5, "title": "Decorate It!", "instruction": f"Use markers to draw eyes, a nose, and a mouth on your {title}. Add anything else you want!", "tip": f"Give your {title} a name!"},
        ]
    elif skill == "intermediate":
        return [
            {"step_number": 1, "title": "Make Fold Lines", "instruction": f"Start with a square paper for your {title}. Fold it corner to corner both ways, then side to side both ways. Open it back up - you'll see a star shape of fold lines.", "tip": "Press hard on every fold to make sharp lines!"},
            {"step_number": 2, "title": "Squish It Down", "instruction": "Use those fold lines to push the paper into a smaller square shape. Push the sides in and flatten it down.", "tip": None},
            {"step_number": 3, "title": "Shape the Body", "instruction": f"Fold the side edges in to the middle line on both sides. This makes a pointy shape that will be the body of your {title}.", "tip": None},
            {"step_number": 4, "title": "Make the Head", "instruction": f"Push one pointy end up to make the neck, then bend the very tip down to make the head of your {title}.", "tip": "The way you bend it changes how your animal looks!"},
            {"step_number": 5, "title": "Add Legs and Tail", "instruction": f"Fold and shape the extra points to make legs, wings, or a tail. Make little zigzag folds to add cool details to your {title}.", "tip": None},
            {"step_number": 6, "title": "Make It 3D!", "instruction": f"Gently pull and bend your {title} so it looks round and real. Move the head and body until it looks just right.", "tip": f"Put your {title} on a shelf to show it off!"},
        ]
    else:
        return [
            {"step_number": 1, "title": "Make a Fold Map", "instruction": f"Start with a big square paper for your {title}. Fold it into four parts both ways and corner to corner. These fold lines are your map!", "tip": "Use thin paper - it's easier for tricky folds!"},
            {"step_number": 2, "title": "Squish into Shape", "instruction": "Push the paper together using your fold lines to make a small pointy base shape. Line everything up carefully.", "tip": None},
            {"step_number": 3, "title": "Lift and Fold", "instruction": "Lift the bottom flap up and fold the sides in at the same time. Do this on all sides to make long skinny points.", "tip": "This is the hardest part - go slow and be patient!"},
            {"step_number": 4, "title": "Shape the Body", "instruction": f"Make the body part skinnier by folding the edges in. Then push-fold to shape the main body of your {title}.", "tip": None},
            {"step_number": 5, "title": "Make the Head", "instruction": f"Bend one point up for the neck, then bend the tip to make the head. Add little folds for horns, ears, or a beak on your {title}.", "tip": None},
            {"step_number": 6, "title": "Arms and Wings", "instruction": f"Shape the legs, wings, or arms by making zigzag folds. Make both sides look the same.", "tip": None},
            {"step_number": 7, "title": "Add Cool Details", "instruction": f"Add tiny folds for things like scales, feathers, or claws to make your {title} look amazing.", "tip": None},
            {"step_number": 8, "title": "Strike a Pose!", "instruction": f"Gently bend your {title} into a cool 3D pose. Curve the wings, bend the neck, and shape the tail. You did it!", "tip": "Try wetting the paper a little for smoother curves!"},
        ]

def _flower_steps(title, skill):
    if skill == "beginner":
        return [
            {"step_number": 1, "title": "Pick a Pretty Color", "instruction": f"Grab a square piece of paper in a pretty color for your {title}. Put it on the table like a diamond.", "tip": "Bright colors make the best flowers!"},
            {"step_number": 2, "title": "Fold a Triangle", "instruction": "Fold one corner over to the other corner to make a triangle. Press the fold down nice and flat.", "tip": None},
            {"step_number": 3, "title": "Make the Petals", "instruction": f"Fold the pointy corners of the triangle up to start making the petals of your {title}.", "tip": "Try to make both sides look the same."},
            {"step_number": 4, "title": "Round It Out", "instruction": f"Fold the sharp edges behind to make your {title} look soft and round, like a real flower.", "tip": None},
            {"step_number": 5, "title": "Add a Stem!", "instruction": f"Roll a thin piece of green paper to make a stem. Stick it on the back of your {title} with tape.", "tip": "Make a whole bunch of flowers in different colors!"},
        ]
    elif skill == "intermediate":
        return [
            {"step_number": 1, "title": "Make Fold Lines", "instruction": f"Start with a square paper for your {title}. Fold it in half both ways and corner to corner both ways. Open it up to see all the fold lines.", "tip": "Use pretty paper for extra beauty!"},
            {"step_number": 2, "title": "Squish into Shape", "instruction": "Push the paper together using the fold lines to make a small triangle or square base shape.", "tip": None},
            {"step_number": 3, "title": "First Petals", "instruction": f"Fold the top parts outward to make the first layer of petals for your {title}.", "tip": "Make each petal the same size."},
            {"step_number": 4, "title": "More Petals", "instruction": f"Fold more layers out to make the outer petals. Each layer should open up a bit more than the one before.", "tip": None},
            {"step_number": 5, "title": "Make the Middle", "instruction": f"Fold or twist the very center paper to make the middle part of your {title}.", "tip": None},
            {"step_number": 6, "title": "Make It Bloom!", "instruction": f"Use a pencil to gently curl each petal outward. Shape your {title} so it looks like it's blooming!", "tip": "Roll petals around a pencil for the best curl!"},
        ]
    else:
        return [
            {"step_number": 1, "title": "Make Fold Lines", "instruction": f"Start with a big square paper for your {title}. Fold it into three or four parts both ways to make a grid of fold lines.", "tip": "Take your time - neat fold lines make a better flower!"},
            {"step_number": 2, "title": "Fold Corners In", "instruction": "Fold all four corners to the middle. Then do it again! And one more time! Now you have lots of layers.", "tip": None},
            {"step_number": 3, "title": "Twist the Middle", "instruction": f"Carefully twist the center of the paper to make a spiral. This will be the heart of your {title}.", "tip": "Go really slowly here - the paper can rip if you rush!"},
            {"step_number": 4, "title": "Pull Out Petals", "instruction": f"Very gently, reach underneath and pull the paper flaps up and out to make the first ring of petals for your {title}.", "tip": None},
            {"step_number": 5, "title": "More Petal Rings", "instruction": "Keep pulling out more layers of petals. Each ring should be a little bigger and more open.", "tip": None},
            {"step_number": 6, "title": "Outside Petals", "instruction": f"Pull out the last ring of petals. Make them spread out wide so your {title} looks full and beautiful.", "tip": None},
            {"step_number": 7, "title": "Curl the Petals", "instruction": f"Wrap each petal around a pencil and let go to make them curl. This makes your {title} look real!", "tip": None},
            {"step_number": 8, "title": "Add Stem and Leaves", "instruction": f"Roll green paper into a thin stem and cut out some leaves. Tape them on to finish your {title}. Beautiful!", "tip": "This flower will never die - it makes a great gift!"},
        ]

def _object_steps(title, skill):
    if skill == "beginner":
        return [
            {"step_number": 1, "title": "Grab Your Paper", "instruction": f"Get a piece of paper for your {title}. Some need rectangle paper, some need square - check which one!", "tip": None},
            {"step_number": 2, "title": "Big Fold", "instruction": f"Fold the paper in half to start making your {title}. Press the fold line down hard.", "tip": "A good fold makes everything easier!"},
            {"step_number": 3, "title": "Shape It Up", "instruction": f"Make more folds to shape your {title}. Follow the lines you already made.", "tip": None},
            {"step_number": 4, "title": "Add the Details", "instruction": f"Fold the smaller parts that make your {title} look like the real thing. Tuck in any loose bits.", "tip": None},
            {"step_number": 5, "title": "All Done!", "instruction": f"Your {title} is finished! Color it with markers or add stickers to make it extra cool.", "tip": "Try making it with different colored paper!"},
        ]
    elif skill == "intermediate":
        return [
            {"step_number": 1, "title": "Get Paper Ready", "instruction": f"Start with a square paper for your {title}. Fold it in half both ways to find the middle, then open it back up.", "tip": "Smooth, thin paper works best!"},
            {"step_number": 2, "title": "Build the Base", "instruction": f"Make the main folds that give your {title} its basic shape. These folds are the building blocks.", "tip": None},
            {"step_number": 3, "title": "Make It 3D", "instruction": f"Keep folding to make your {title} pop up into a 3D shape. It should start looking like the real thing!", "tip": "Take your time here - it's the tricky part!"},
            {"step_number": 4, "title": "Clean It Up", "instruction": f"Make careful folds to clean up the edges and shape of your {title}.", "tip": None},
            {"step_number": 5, "title": "Lock It Together", "instruction": f"Tuck all the flaps in and fold the last pieces to hold your {title} together tight.", "tip": None},
            {"step_number": 6, "title": "Final Touches", "instruction": f"Fix up anything that looks off and show off your finished {title}!", "tip": "Try making it with shiny or patterned paper!"},
        ]
    else:
        return [
            {"step_number": 1, "title": "Map Out the Folds", "instruction": f"Make all the fold lines you'll need for your {title}. Fold the paper into a grid and corner to corner.", "tip": "Use big paper (bigger than your hand) for tricky models!"},
            {"step_number": 2, "title": "Push It Together", "instruction": "Use all those fold lines to push the paper together into the starting shape. Everything should line up.", "tip": None},
            {"step_number": 3, "title": "Build the Main Part", "instruction": f"Shape the biggest part of your {title} first. Fold the edges in and lift flaps up.", "tip": None},
            {"step_number": 4, "title": "Add More Parts", "instruction": f"Now add the smaller parts and details that make your {title} look special.", "tip": "If you get lost, go back and check your fold lines."},
            {"step_number": 5, "title": "Tiny Details", "instruction": f"Make really small, careful folds for the tiny details on your {title}.", "tip": None},
            {"step_number": 6, "title": "Make It Pop", "instruction": f"Gently push and pull your {title} into its final 3D shape. Bend curves and fix angles.", "tip": None},
            {"step_number": 7, "title": "Show It Off!", "instruction": f"Your {title} is done! Make any last little fixes and find a great spot to display it.", "tip": "Slightly damp paper can help make smoother curves!"},
        ]

def get_steps(category, skill, title):
    fn = {"animal": _animal_steps, "flower": _flower_steps, "object": _object_steps}
    return fn.get(category, _object_steps)(title, skill)

# Color palette
C = {
    "red": "#EF4444", "rose": "#FB7185", "pink": "#EC4899", "fuchsia": "#D946EF",
    "purple": "#A855F7", "violet": "#8B5CF6", "indigo": "#6366F1", "blue": "#3B82F6",
    "sky": "#38BDF8", "cyan": "#06B6D4", "teal": "#14B8A6", "emerald": "#10B981",
    "green": "#22C55E", "lime": "#84CC16", "yellow": "#EAB308", "amber": "#F59E0B",
    "orange": "#F97316", "coral": "#FB923C",
}

# Icons available in Ionicons
ICONS = ["paw", "fish", "leaf", "flower", "heart", "star", "flame", "moon",
         "snow", "airplane", "boat", "paper-plane", "diamond", "gift", "musical-note",
         "cube", "rocket", "car", "home", "shirt", "umbrella", "sunny", "rainy",
         "globe", "ribbon", "trophy", "flash", "sparkles", "pizza", "ice-cream"]

def _i(idx):
    return ICONS[idx % len(ICONS)]

# All 200+ origami projects (id, title, cat, skill, season, holiday, diff, time, premium, icon_idx, color_key, desc)
RAW = [
    # ===== ANIMALS - BEGINNER (25) =====
    ("puppy-face", "Puppy Face", "animal", "beginner", "all", None, 1, 5, False, 0, "coral", "Create an adorable puppy face with floppy ears!"),
    ("kitty-cat", "Kitty Cat", "animal", "beginner", "all", None, 1, 5, False, 0, "violet", "A sweet cat face with pointy ears and whiskers!"),
    ("simple-fish", "Simple Fish", "animal", "beginner", "summer", None, 1, 5, False, 1, "blue", "A colorful fish that looks great swimming on paper!"),
    ("little-bird", "Little Bird", "animal", "beginner", "spring", None, 1, 5, False, 2, "sky", "A cheerful little bird sitting on a branch!"),
    ("bunny-rabbit", "Bunny Rabbit", "animal", "beginner", "spring", "easter", 2, 8, False, 0, "pink", "A cute bunny with long floppy ears!"),
    ("quacking-duck", "Quacking Duck", "animal", "beginner", "all", None, 1, 5, False, 0, "yellow", "A yellow duck ready to swim in the pond!"),
    ("tiny-penguin", "Tiny Penguin", "animal", "beginner", "winter", None, 2, 8, False, 0, "indigo", "A tuxedo-wearing penguin from the South Pole!"),
    ("blue-whale", "Blue Whale", "animal", "beginner", "summer", None, 2, 8, False, 1, "blue", "The biggest animal in the ocean - in paper form!"),
    ("mouse-friend", "Mouse Friend", "animal", "beginner", "all", None, 1, 5, False, 0, "coral", "A tiny mouse with big round ears!"),
    ("bear-cub", "Bear Cub", "animal", "beginner", "fall", None, 2, 8, False, 0, "amber", "A fluffy little bear cub!"),
    ("silly-snake", "Silly Snake", "animal", "beginner", "summer", None, 1, 5, False, 2, "green", "A wiggly snake that's easy and fun to make!"),
    ("baby-turtle", "Baby Turtle", "animal", "beginner", "summer", None, 2, 8, False, 0, "teal", "A cute turtle with a patterned shell!"),
    ("piggy-pink", "Piggy Pink", "animal", "beginner", "all", None, 1, 5, False, 0, "pink", "An oink-worthy little pig face!"),
    ("baby-elephant", "Baby Elephant", "animal", "beginner", "all", None, 2, 8, False, 0, "violet", "A big-eared baby elephant!"),
    ("ladybug-friend", "Ladybug Friend", "animal", "beginner", "spring", None, 1, 5, False, 0, "red", "A spotted ladybug to bring you good luck!"),
    ("frog-face", "Frog Face", "animal", "beginner", "spring", None, 1, 5, False, 2, "green", "Ribbit! A green frog face!"),
    ("baby-chick", "Baby Chick", "animal", "beginner", "spring", "easter", 1, 5, False, 0, "yellow", "A fluffy yellow chick just hatched!"),
    ("seal-pup", "Seal Pup", "animal", "beginner", "winter", None, 2, 8, False, 1, "violet", "A playful seal pup on the ice!"),
    ("hedgehog-pal", "Hedgehog Pal", "animal", "beginner", "fall", None, 2, 8, False, 0, "amber", "A spiky but friendly hedgehog!"),
    ("hamster-cheeks", "Hamster Cheeks", "animal", "beginner", "all", None, 1, 5, False, 0, "coral", "A hamster with chubby cheeks full of food!"),
    ("goldfish", "Goldfish", "animal", "beginner", "all", None, 1, 5, False, 1, "orange", "A sparkly goldfish for your desk!"),
    ("robin-bird", "Robin Red", "animal", "beginner", "spring", None, 2, 8, False, 2, "red", "A robin redbreast to welcome spring!"),
    ("panda-face", "Panda Face", "animal", "beginner", "all", None, 2, 8, False, 0, "indigo", "A black and white panda face!"),
    ("starfish", "Starfish", "animal", "beginner", "summer", None, 1, 5, False, 4, "coral", "A five-armed starfish from the beach!"),
    ("snail-trail", "Snail Trail", "animal", "beginner", "spring", None, 2, 8, False, 0, "amber", "A slow and steady garden snail!"),
    # ===== ANIMALS - INTERMEDIATE (25) =====
    ("crane-001", "Paper Crane", "animal", "intermediate", "all", None, 3, 15, True, 11, "sky", "The classic crane - fold 1000 for a wish!"),
    ("jumping-frog", "Jumping Frog", "animal", "intermediate", "spring", None, 3, 12, False, 2, "green", "This frog actually jumps when you press it!"),
    ("butterfly-001", "Beautiful Butterfly", "animal", "intermediate", "spring", None, 3, 12, True, 2, "fuchsia", "A graceful butterfly with delicate wings!"),
    ("clever-fox", "Clever Fox", "animal", "intermediate", "fall", None, 2, 8, False, 0, "orange", "A sly fox with pointy ears!"),
    ("wise-owl", "Wise Owl", "animal", "intermediate", "fall", None, 3, 12, False, 0, "amber", "A wise owl watching from its tree!"),
    ("galloping-horse", "Galloping Horse", "animal", "intermediate", "all", None, 3, 15, True, 0, "amber", "A majestic horse mid-gallop!"),
    ("leaping-dolphin", "Leaping Dolphin", "animal", "intermediate", "summer", None, 3, 12, False, 1, "blue", "A dolphin jumping out of the water!"),
    ("soaring-eagle", "Soaring Eagle", "animal", "intermediate", "all", None, 3, 15, True, 11, "amber", "A powerful eagle with spread wings!"),
    ("colorful-parrot", "Colorful Parrot", "animal", "intermediate", "summer", None, 3, 12, False, 0, "green", "A tropical parrot with vivid feathers!"),
    ("elegant-swan", "Elegant Swan", "animal", "intermediate", "all", None, 3, 12, True, 11, "violet", "A graceful swan gliding on water!"),
    ("crab-claws", "Crab Claws", "animal", "intermediate", "summer", None, 3, 12, False, 1, "red", "A crab with snapping claws!"),
    ("octopus-arms", "Octopus Arms", "animal", "intermediate", "summer", None, 3, 15, False, 1, "purple", "An eight-armed ocean friend!"),
    ("spooky-bat", "Spooky Bat", "animal", "intermediate", "fall", "halloween", 3, 10, False, 7, "indigo", "Spread-winged bat for Halloween!"),
    ("howling-wolf", "Howling Wolf", "animal", "intermediate", "winter", None, 3, 12, False, 0, "violet", "A wolf howling at the moon!"),
    ("forest-deer", "Forest Deer", "animal", "intermediate", "fall", None, 3, 15, True, 0, "amber", "A deer with majestic antlers!"),
    ("hummingbird", "Hummingbird", "animal", "intermediate", "spring", None, 3, 12, False, 11, "emerald", "A tiny bird hovering near flowers!"),
    ("sea-turtle", "Sea Turtle", "animal", "intermediate", "summer", None, 3, 12, False, 1, "teal", "A gentle sea turtle swimming along!"),
    ("koala-bear", "Koala Bear", "animal", "intermediate", "all", None, 3, 12, False, 0, "violet", "A cuddly koala hugging a tree!"),
    ("flamingo", "Pink Flamingo", "animal", "intermediate", "summer", None, 3, 15, True, 0, "pink", "A one-legged flamingo standing tall!"),
    ("rooster", "Morning Rooster", "animal", "intermediate", "all", None, 3, 12, False, 0, "red", "Cock-a-doodle-doo! A proud rooster!"),
    ("dragonfly", "Dragonfly", "animal", "intermediate", "summer", None, 3, 12, False, 2, "sky", "A dragonfly with translucent wings!"),
    ("shark-fin", "Great Shark", "animal", "intermediate", "summer", None, 3, 15, True, 1, "blue", "A fearsome shark cutting through waves!"),
    ("raccoon", "Masked Raccoon", "animal", "intermediate", "fall", None, 3, 12, False, 0, "violet", "A mischievous raccoon with its mask!"),
    ("pelican", "Pelican", "animal", "intermediate", "summer", None, 3, 12, False, 11, "amber", "A pelican with a huge beak pouch!"),
    ("stingray", "Stingray", "animal", "intermediate", "summer", None, 3, 12, False, 1, "indigo", "A graceful stingray gliding underwater!"),
    # ===== ANIMALS - ADVANCED (20) =====
    ("dragon-001", "Fire Dragon", "animal", "advanced", "all", None, 5, 30, True, 8, "red", "The ultimate challenge - a fearsome dragon!"),
    ("phoenix-rise", "Phoenix Rising", "animal", "advanced", "all", None, 5, 30, True, 8, "orange", "A mythical phoenix rising from flames!"),
    ("unicorn", "Magical Unicorn", "animal", "advanced", "all", None, 5, 25, True, 0, "fuchsia", "A magical unicorn with a spiral horn!"),
    ("t-rex", "T-Rex Dinosaur", "animal", "advanced", "all", None, 5, 30, True, 0, "green", "A terrifying T-Rex from prehistory!"),
    ("lion-king", "Lion King", "animal", "advanced", "all", None, 5, 25, True, 0, "amber", "The king of the jungle with a glorious mane!"),
    ("tiger-stripe", "Striped Tiger", "animal", "advanced", "all", None, 5, 25, True, 0, "orange", "A powerful tiger ready to pounce!"),
    ("scorpion", "Desert Scorpion", "animal", "advanced", "summer", None, 4, 20, True, 0, "amber", "A scorpion with a curled stinger tail!"),
    ("praying-mantis", "Praying Mantis", "animal", "advanced", "fall", None, 5, 30, True, 2, "green", "An intricate praying mantis!"),
    ("chameleon", "Color Chameleon", "animal", "advanced", "all", None, 4, 25, True, 0, "emerald", "A chameleon on a branch!"),
    ("pegasus", "Flying Pegasus", "animal", "advanced", "all", None, 5, 30, True, 0, "sky", "A winged horse soaring through clouds!"),
    ("pterodactyl", "Pterodactyl", "animal", "advanced", "all", None, 5, 30, True, 11, "violet", "A flying dinosaur from the Jurassic!"),
    ("koi-fish", "Koi Fish", "animal", "advanced", "spring", None, 4, 20, True, 1, "red", "A beautiful Japanese koi fish!"),
    ("stag-beetle", "Stag Beetle", "animal", "advanced", "summer", None, 5, 30, True, 0, "indigo", "A beetle with impressive mandibles!"),
    ("spider-web", "Garden Spider", "animal", "advanced", "fall", "halloween", 4, 25, True, 0, "indigo", "A spider hanging from its web!"),
    ("peacock-001", "Royal Peacock", "animal", "advanced", "all", None, 5, 30, True, 0, "teal", "A peacock with a full fan tail display!"),
    ("griffin", "Mythical Griffin", "animal", "advanced", "all", None, 5, 35, True, 8, "amber", "Half eagle, half lion - a legendary creature!"),
    ("centaur", "Centaur Warrior", "animal", "advanced", "all", None, 5, 35, True, 0, "amber", "A mythical half-human, half-horse warrior!"),
    ("triceratops", "Triceratops", "animal", "advanced", "all", None, 5, 30, True, 0, "green", "A three-horned dinosaur!"),
    ("seahorse", "Elegant Seahorse", "animal", "advanced", "summer", None, 4, 25, True, 1, "purple", "A curly-tailed seahorse!"),
    ("eagle-owl", "Great Eagle Owl", "animal", "advanced", "winter", None, 5, 30, True, 0, "amber", "A majestic owl with ear tufts!"),
    # ===== FLOWERS - BEGINNER (15) =====
    ("tulip-001", "Spring Tulip", "flower", "beginner", "spring", "easter", 2, 10, False, 3, "pink", "A beautiful tulip to celebrate spring!"),
    ("simple-daisy", "Simple Daisy", "flower", "beginner", "spring", None, 1, 8, False, 3, "yellow", "A cheerful daisy with white petals!"),
    ("green-leaf", "Green Leaf", "flower", "beginner", "fall", None, 1, 5, False, 2, "green", "A simple green leaf - great for beginners!"),
    ("rosebud", "Little Rosebud", "flower", "beginner", "spring", "valentines", 2, 8, False, 3, "rose", "A small rosebud just about to bloom!"),
    ("clover-luck", "Lucky Clover", "flower", "beginner", "spring", None, 2, 8, False, 2, "green", "A four-leaf clover for good luck!"),
    ("water-lily-pad", "Lily Pad", "flower", "beginner", "summer", None, 1, 5, False, 2, "emerald", "A floating lily pad for a paper pond!"),
    ("pine-tree", "Pine Tree", "flower", "beginner", "winter", "christmas", 2, 10, False, 2, "green", "An evergreen pine tree!"),
    ("little-sprout", "Little Sprout", "flower", "beginner", "spring", None, 1, 5, False, 2, "lime", "A tiny plant just sprouting!"),
    ("simple-cactus", "Desert Cactus", "flower", "beginner", "summer", None, 2, 8, False, 2, "green", "A prickly cactus that won't hurt!"),
    ("dandelion-puff", "Dandelion Puff", "flower", "beginner", "spring", None, 1, 5, False, 3, "yellow", "A fluffy dandelion ready to blow!"),
    ("sunflower-face", "Sunflower Face", "flower", "beginner", "summer", None, 2, 10, False, 3, "yellow", "A big happy sunflower!"),
    ("mushroom", "Woodland Mushroom", "flower", "beginner", "fall", None, 2, 8, False, 0, "red", "A spotted woodland mushroom!"),
    ("palm-tree", "Palm Tree", "flower", "beginner", "summer", None, 2, 10, False, 2, "green", "A tropical palm tree!"),
    ("autumn-leaf", "Autumn Leaf", "flower", "beginner", "fall", None, 1, 5, False, 2, "orange", "A colorful falling autumn leaf!"),
    ("bamboo-stalk", "Bamboo Stalk", "flower", "beginner", "all", None, 2, 8, False, 2, "emerald", "A tall bamboo stalk!"),
    # ===== FLOWERS - INTERMEDIATE (15) =====
    ("cherry-blossom", "Cherry Blossom", "flower", "intermediate", "spring", None, 3, 12, True, 3, "pink", "A delicate Japanese cherry blossom!"),
    ("lily-flower", "Lily Flower", "flower", "intermediate", "spring", None, 3, 12, False, 3, "violet", "An elegant lily with curved petals!"),
    ("iris-bloom", "Iris Bloom", "flower", "intermediate", "spring", None, 3, 12, False, 3, "purple", "A regal purple iris!"),
    ("carnation", "Frilly Carnation", "flower", "intermediate", "all", "valentines", 3, 15, True, 3, "rose", "A carnation with ruffled petals!"),
    ("daffodil", "Golden Daffodil", "flower", "intermediate", "spring", None, 3, 12, False, 3, "yellow", "A trumpet-shaped daffodil!"),
    ("hibiscus", "Tropical Hibiscus", "flower", "intermediate", "summer", None, 3, 12, False, 3, "red", "A bright tropical hibiscus flower!"),
    ("lavender-sprig", "Lavender Sprig", "flower", "intermediate", "summer", None, 3, 12, False, 3, "purple", "A fragrant lavender sprig!"),
    ("poppy-red", "Red Poppy", "flower", "intermediate", "spring", None, 3, 12, False, 3, "red", "A bold red poppy flower!"),
    ("bluebell", "Bluebell", "flower", "intermediate", "spring", None, 3, 12, False, 3, "blue", "A delicate woodland bluebell!"),
    ("maple-leaf", "Maple Leaf", "flower", "intermediate", "fall", None, 3, 12, False, 2, "red", "A five-pointed maple leaf!"),
    ("oak-leaf", "Oak Leaf", "flower", "intermediate", "fall", None, 3, 12, False, 2, "amber", "A sturdy oak leaf!"),
    ("fern-frond", "Fern Frond", "flower", "intermediate", "all", None, 3, 12, False, 2, "emerald", "A curling fern frond!"),
    ("poinsettia", "Poinsettia", "flower", "intermediate", "winter", "christmas", 3, 15, True, 3, "red", "A festive Christmas poinsettia!"),
    ("holly-berry", "Holly Berry", "flower", "intermediate", "winter", "christmas", 3, 12, False, 2, "green", "Holly with red berries for the holidays!"),
    ("snowflake-001", "Winter Snowflake", "flower", "intermediate", "winter", "christmas", 3, 10, False, 8, "sky", "Every snowflake is unique - just like yours!"),
    # ===== FLOWERS - ADVANCED (10) =====
    ("rose-001", "Elegant Rose", "flower", "advanced", "spring", "valentines", 5, 25, True, 3, "rose", "A stunningly realistic paper rose!"),
    ("lotus-001", "Lotus Flower", "flower", "advanced", "summer", None, 4, 20, True, 3, "pink", "A serene lotus floating on water!"),
    ("orchid", "Orchid", "flower", "advanced", "all", None, 5, 25, True, 3, "fuchsia", "An exotic orchid with intricate petals!"),
    ("chrysanthemum", "Chrysanthemum", "flower", "advanced", "fall", None, 5, 25, True, 3, "amber", "A many-petaled chrysanthemum!"),
    ("peony-bloom", "Peony Bloom", "flower", "advanced", "spring", None, 5, 25, True, 3, "pink", "A lush, full peony in bloom!"),
    ("bonsai-tree", "Bonsai Tree", "flower", "advanced", "all", None, 5, 30, True, 2, "green", "A miniature bonsai tree sculpture!"),
    ("bouquet", "Flower Bouquet", "flower", "advanced", "spring", "valentines", 5, 30, True, 3, "rose", "A complete bouquet of paper flowers!"),
    ("venus-flytrap", "Venus Flytrap", "flower", "advanced", "summer", None, 4, 20, True, 2, "green", "A snapping venus flytrap plant!"),
    ("wreath", "Holiday Wreath", "flower", "advanced", "winter", "christmas", 5, 30, True, 2, "green", "A decorative modular wreath!"),
    ("succulent", "Succulent Plant", "flower", "advanced", "all", None, 4, 20, True, 2, "teal", "A trendy succulent in a paper pot!"),
    # ===== OBJECTS - BEGINNER (25) =====
    ("airplane-001", "Paper Airplane", "object", "beginner", "all", None, 1, 5, False, 10, "green", "The classic paper airplane that flies far!"),
    ("boat-001", "Sailing Boat", "object", "beginner", "summer", None, 1, 8, False, 11, "sky", "A boat that can actually float!"),
    ("heart-001", "Love Heart", "object", "beginner", "all", "valentines", 2, 8, False, 4, "rose", "A sweet paper heart!"),
    ("paper-cup", "Paper Cup", "object", "beginner", "all", None, 1, 5, False, 0, "sky", "A cup that actually holds water briefly!"),
    ("party-hat", "Party Hat", "object", "beginner", "all", None, 1, 5, False, 0, "yellow", "A cone-shaped party hat!"),
    ("paper-crown", "Royal Crown", "object", "beginner", "all", None, 2, 8, False, 0, "yellow", "A crown fit for a king or queen!"),
    ("bookmark", "Corner Bookmark", "object", "beginner", "all", None, 1, 5, False, 0, "sky", "Never lose your place again!"),
    ("envelope", "Secret Envelope", "object", "beginner", "all", "valentines", 2, 8, False, 0, "rose", "An envelope for secret messages!"),
    ("paper-fan", "Cooling Fan", "object", "beginner", "summer", None, 1, 5, False, 0, "cyan", "Stay cool with a paper fan!"),
    ("tiny-house", "Tiny House", "object", "beginner", "all", None, 2, 10, False, 14, "coral", "A cute little paper house!"),
    ("paper-shirt", "Paper Shirt", "object", "beginner", "all", None, 2, 8, False, 0, "sky", "A mini shirt from paper!"),
    ("simple-box", "Simple Box", "object", "beginner", "all", None, 2, 10, False, 13, "teal", "A box to store small treasures!"),
    ("pinwheel", "Spinning Pinwheel", "object", "beginner", "spring", None, 2, 10, False, 0, "sky", "A pinwheel that spins in the wind!"),
    ("finger-puppet", "Finger Puppet", "object", "beginner", "all", None, 1, 5, False, 0, "coral", "A puppet that fits on your finger!"),
    ("paper-ball", "Paper Ball", "object", "beginner", "all", None, 2, 8, False, 13, "green", "A round paper ball to play with!"),
    ("paper-ring", "Paper Ring", "object", "beginner", "all", None, 1, 5, False, 12, "yellow", "A ring made from folded paper!"),
    ("arrow-dart", "Arrow Dart", "object", "beginner", "all", None, 1, 5, False, 10, "red", "A quick paper dart that flies straight!"),
    ("paper-boat-2", "Speed Boat", "object", "beginner", "summer", None, 2, 8, False, 11, "blue", "A faster paper boat design!"),
    ("fortune-cookie", "Fortune Cookie", "object", "beginner", "all", None, 1, 5, False, 0, "yellow", "Write a fortune inside!"),
    ("paper-basket", "Mini Basket", "object", "beginner", "spring", "easter", 2, 10, False, 0, "green", "A tiny basket for Easter eggs!"),
    ("magic-wand", "Magic Wand", "object", "beginner", "all", None, 1, 5, False, 15, "fuchsia", "A wand for casting paper spells!"),
    ("paper-wallet", "Paper Wallet", "object", "beginner", "all", None, 2, 8, False, 0, "amber", "A working wallet from paper!"),
    ("paper-plane-2", "Stealth Jet", "object", "beginner", "all", None, 2, 8, False, 10, "violet", "An advanced paper airplane design!"),
    ("paper-sword", "Mini Sword", "object", "beginner", "all", None, 2, 8, False, 0, "violet", "A tiny paper sword for play!"),
    ("paper-bow", "Paper Bow", "object", "beginner", "all", "christmas", 2, 8, False, 12, "red", "A decorative bow for gifts!"),
    # ===== OBJECTS - INTERMEDIATE (20) =====
    ("ninja-star", "Ninja Star", "object", "intermediate", "all", None, 3, 12, False, 4, "red", "A throwing star from two pieces of paper!"),
    ("fortune-teller", "Fortune Teller", "object", "intermediate", "all", None, 3, 10, False, 0, "purple", "Ask it a question and find your fortune!"),
    ("photo-frame", "Photo Frame", "object", "intermediate", "all", None, 3, 12, False, 0, "amber", "Frame your favorite photo in paper!"),
    ("lantern", "Paper Lantern", "object", "intermediate", "fall", None, 3, 12, False, 0, "yellow", "A glowing paper lantern!"),
    ("windmill", "Windmill", "object", "intermediate", "spring", None, 3, 12, False, 0, "blue", "A windmill with spinning blades!"),
    ("rocket-ship", "Rocket Ship", "object", "intermediate", "all", None, 3, 12, True, 16, "red", "Blast off into paper space!"),
    ("star-001", "Christmas Star", "object", "intermediate", "winter", "christmas", 3, 15, False, 5, "yellow", "A beautiful 3D star for the tree!"),
    ("gift-box", "Gift Box", "object", "intermediate", "winter", "christmas", 3, 15, True, 13, "red", "A real box to put presents in!"),
    ("candy-cane", "Candy Cane", "object", "intermediate", "winter", "christmas", 3, 12, False, 0, "red", "A striped candy cane decoration!"),
    ("witch-hat", "Witch Hat", "object", "intermediate", "fall", "halloween", 3, 12, False, 0, "purple", "A pointy witch hat for Halloween!"),
    ("ghost", "Friendly Ghost", "object", "intermediate", "fall", "halloween", 3, 10, False, 0, "violet", "Boo! A friendly paper ghost!"),
    ("jack-o-lantern", "Jack-o-Lantern", "object", "intermediate", "fall", "halloween", 3, 12, False, 0, "orange", "A grinning Halloween pumpkin!"),
    ("santa-hat", "Santa Hat", "object", "intermediate", "winter", "christmas", 3, 12, False, 0, "red", "Ho ho ho! A Santa hat!"),
    ("angel-wings", "Paper Angel", "object", "intermediate", "winter", "christmas", 3, 15, True, 0, "yellow", "A heavenly angel for the tree top!"),
    ("love-letter", "Love Letter", "object", "intermediate", "all", "valentines", 3, 12, False, 4, "rose", "A heart-shaped letter holder!"),
    ("easter-egg", "Easter Egg", "object", "intermediate", "spring", "easter", 3, 12, False, 0, "pink", "A decorated Easter egg!"),
    ("bell", "Jingle Bell", "object", "intermediate", "winter", "christmas", 3, 12, False, 0, "yellow", "A jingling Christmas bell!"),
    ("ice-cream-cone", "Ice Cream Cone", "object", "intermediate", "summer", None, 3, 12, False, 0, "coral", "A delicious paper ice cream!"),
    ("popsicle", "Summer Popsicle", "object", "intermediate", "summer", None, 3, 10, False, 0, "rose", "A cool popsicle treat!"),
    ("trophy-cup", "Trophy Cup", "object", "intermediate", "all", None, 3, 15, True, 17, "yellow", "A winner's trophy cup!"),
    # ===== OBJECTS - ADVANCED (15) =====
    ("grand-piano", "Grand Piano", "object", "advanced", "all", None, 5, 30, True, 14, "indigo", "A detailed miniature grand piano!"),
    ("violin", "Violin", "object", "advanced", "all", None, 5, 30, True, 14, "amber", "A beautifully detailed violin!"),
    ("paper-castle", "Castle Tower", "object", "advanced", "all", None, 5, 35, True, 14, "violet", "A medieval castle with towers!"),
    ("robot", "Paper Robot", "object", "advanced", "all", None, 4, 25, True, 13, "sky", "A boxy robot friend!"),
    ("paper-camera", "Camera", "object", "advanced", "all", None, 4, 25, True, 0, "indigo", "A paper camera with a lens!"),
    ("guitar", "Acoustic Guitar", "object", "advanced", "all", None, 5, 30, True, 14, "amber", "A guitar ready to play!"),
    ("sailship", "Sailing Ship", "object", "advanced", "summer", None, 5, 35, True, 11, "blue", "A tall ship with multiple sails!"),
    ("modular-cube", "Modular Cube", "object", "advanced", "all", None, 4, 20, True, 13, "purple", "A 3D cube from 6 paper modules!"),
    ("kusudama-ball", "Kusudama Ball", "object", "advanced", "all", None, 5, 35, True, 12, "fuchsia", "A stunning modular flower ball!"),
    ("chess-piece", "Chess King", "object", "advanced", "all", None, 5, 30, True, 0, "indigo", "A chess king piece with crown!"),
    ("paper-clock", "Paper Clock", "object", "advanced", "all", None, 4, 25, True, 0, "amber", "A clock face with moving hands!"),
    ("paper-mask", "Theater Mask", "object", "advanced", "all", "halloween", 4, 25, True, 0, "yellow", "A dramatic theater mask!"),
    ("samurai-helmet", "Samurai Helmet", "object", "advanced", "all", None, 4, 20, True, 0, "red", "A traditional samurai kabuto helmet!"),
    ("paper-shoe", "Paper Shoe", "object", "advanced", "all", None, 4, 25, True, 0, "coral", "A miniature paper shoe!"),
    ("treasure-chest", "Treasure Chest", "object", "advanced", "all", None, 5, 30, True, 13, "amber", "A chest to store your paper treasures!"),
    # ===== PREMIUM ANIMALS (50) =====
    ("p-wolf-howl", "Howling Wolf", "animal", "intermediate", "winter", None, 3, 15, True, 0, "violet", "A wolf howling at the big round moon!"),
    ("p-baby-dragon", "Baby Dragon", "animal", "intermediate", "all", None, 3, 15, True, 8, "red", "A cute baby dragon with tiny wings!"),
    ("p-arctic-fox", "Arctic Fox", "animal", "intermediate", "winter", None, 3, 12, True, 0, "sky", "A fluffy white arctic fox in the snow!"),
    ("p-red-panda", "Red Panda", "animal", "intermediate", "fall", None, 3, 15, True, 0, "orange", "A fluffy red panda munching bamboo!"),
    ("p-narwhal", "Magical Narwhal", "animal", "intermediate", "winter", None, 3, 15, True, 1, "purple", "A narwhal with a sparkly horn!"),
    ("p-axolotl", "Cute Axolotl", "animal", "beginner", "all", None, 2, 10, True, 1, "pink", "A smiley pink axolotl swimming around!"),
    ("p-capybara", "Chill Capybara", "animal", "beginner", "summer", None, 2, 10, True, 0, "amber", "The chillest animal ever - a capybara!"),
    ("p-otter", "Sea Otter", "animal", "intermediate", "summer", None, 3, 12, True, 1, "amber", "A sea otter floating on its back!"),
    ("p-sloth", "Sleepy Sloth", "animal", "beginner", "all", None, 2, 8, True, 0, "green", "A super slow and super cute sloth!"),
    ("p-corgi", "Corgi Dog", "animal", "beginner", "all", None, 2, 10, True, 0, "coral", "A short-legged fluffy corgi!"),
    ("p-llama", "Fluffy Llama", "animal", "intermediate", "all", None, 3, 12, True, 0, "pink", "A llama with a fluffy neck!"),
    ("p-toucan", "Toucan Bird", "animal", "intermediate", "summer", None, 3, 12, True, 0, "orange", "A toucan with a big colorful beak!"),
    ("p-jellyfish", "Jellyfish", "animal", "beginner", "summer", None, 2, 10, True, 1, "purple", "A see-through jellyfish with long tentacles!"),
    ("p-caterpillar", "Caterpillar", "animal", "beginner", "spring", None, 1, 8, True, 2, "green", "A wiggly caterpillar that turns into a butterfly!"),
    ("p-gorilla", "Mighty Gorilla", "animal", "advanced", "all", None, 4, 25, True, 0, "indigo", "A strong gorilla beating its chest!"),
    ("p-giraffe", "Tall Giraffe", "animal", "intermediate", "all", None, 3, 15, True, 0, "yellow", "The tallest animal with a super long neck!"),
    ("p-hippo", "Happy Hippo", "animal", "intermediate", "summer", None, 3, 12, True, 0, "violet", "A big happy hippo splashing in water!"),
    ("p-zebra", "Striped Zebra", "animal", "intermediate", "all", None, 3, 15, True, 0, "indigo", "A zebra with cool black and white stripes!"),
    ("p-manta-ray", "Manta Ray", "animal", "advanced", "summer", None, 4, 20, True, 1, "blue", "A giant manta ray gliding through the ocean!"),
    ("p-hammerhead", "Hammerhead Shark", "animal", "advanced", "summer", None, 4, 20, True, 1, "blue", "A shark with the weirdest head shape ever!"),
    ("p-bald-eagle", "Bald Eagle", "animal", "advanced", "all", None, 5, 25, True, 0, "amber", "America's proud bald eagle!"),
    ("p-puffin", "Puffin Bird", "animal", "intermediate", "winter", None, 3, 12, True, 0, "coral", "A cute puffin with a colorful beak!"),
    ("p-chameleon2", "Color Chameleon", "animal", "advanced", "all", None, 4, 20, True, 0, "green", "A chameleon changing colors on a branch!"),
    ("p-rhino", "Rhinoceros", "animal", "advanced", "all", None, 5, 25, True, 0, "violet", "A mighty rhino with a big horn!"),
    ("p-moose", "Big Moose", "animal", "advanced", "fall", None, 5, 25, True, 0, "amber", "A moose with giant antlers!"),
    ("p-platypus", "Platypus", "animal", "intermediate", "all", None, 3, 15, True, 0, "teal", "The weirdest animal - half duck half beaver!"),
    ("p-chinchilla", "Fluffy Chinchilla", "animal", "beginner", "all", None, 2, 10, True, 0, "violet", "The softest fluffiest chinchilla!"),
    ("p-fennec-fox", "Fennec Fox", "animal", "intermediate", "summer", None, 3, 12, True, 0, "yellow", "A tiny fox with huge ears!"),
    ("p-manatee", "Gentle Manatee", "animal", "intermediate", "summer", None, 3, 12, True, 1, "teal", "A big gentle sea cow floating along!"),
    ("p-pangolin", "Pangolin", "animal", "advanced", "all", None, 4, 20, True, 0, "amber", "A scaly pangolin all curled up in a ball!"),
    ("p-snow-leopard", "Snow Leopard", "animal", "advanced", "winter", None, 5, 30, True, 0, "violet", "A beautiful spotted snow leopard!"),
    ("p-albatross", "Albatross", "animal", "advanced", "summer", None, 4, 20, True, 11, "sky", "A bird with the longest wings in the world!"),
    ("p-komodo", "Komodo Dragon", "animal", "advanced", "all", None, 5, 25, True, 0, "green", "The biggest lizard on Earth!"),
    ("p-quokka", "Happy Quokka", "animal", "beginner", "all", None, 2, 8, True, 0, "coral", "The happiest animal - always smiling!"),
    ("p-blue-jay", "Blue Jay", "animal", "intermediate", "fall", None, 3, 12, True, 0, "blue", "A bright blue jay with a cool crest!"),
    ("p-red-fox", "Red Fox", "animal", "intermediate", "fall", None, 3, 12, True, 0, "red", "A clever red fox sneaking through the forest!"),
    ("p-arctic-hare", "Arctic Hare", "animal", "beginner", "winter", None, 2, 10, True, 0, "sky", "A white bunny that lives in the snow!"),
    ("p-firefly", "Glowing Firefly", "animal", "beginner", "summer", None, 2, 8, True, 2, "yellow", "A firefly that lights up at night!"),
    ("p-tree-frog", "Tree Frog", "animal", "intermediate", "spring", None, 3, 12, True, 2, "lime", "A bright green tree frog on a leaf!"),
    ("p-emperor-penguin", "Emperor Penguin", "animal", "intermediate", "winter", None, 3, 15, True, 0, "indigo", "The biggest and fanciest penguin!"),
    ("p-clownfish", "Clownfish", "animal", "beginner", "summer", None, 2, 10, True, 1, "orange", "Nemo! A cute orange and white clownfish!"),
    ("p-barn-owl", "Barn Owl", "animal", "intermediate", "fall", None, 3, 15, True, 0, "amber", "A mysterious barn owl with a heart face!"),
    ("p-poison-frog", "Poison Dart Frog", "animal", "intermediate", "summer", None, 3, 12, True, 2, "blue", "A tiny super colorful poison frog!"),
    ("p-mammoth", "Woolly Mammoth", "animal", "advanced", "winter", None, 5, 30, True, 0, "amber", "A huge woolly mammoth from long long ago!"),
    ("p-velociraptor", "Velociraptor", "animal", "advanced", "all", None, 5, 25, True, 0, "green", "A fast and sneaky dinosaur!"),
    ("p-kraken", "Giant Kraken", "animal", "advanced", "summer", None, 5, 30, True, 1, "indigo", "A giant sea monster with lots of arms!"),
    ("p-dove", "Peace Dove", "animal", "beginner", "all", None, 2, 10, True, 11, "sky", "A white dove carrying an olive branch!"),
    ("p-cardinal", "Red Cardinal", "animal", "intermediate", "winter", "christmas", 3, 12, True, 0, "red", "A bright red cardinal in the snow!"),
    ("p-butterfly-monarch", "Monarch Butterfly", "animal", "intermediate", "spring", None, 3, 15, True, 2, "orange", "A beautiful orange monarch butterfly!"),
    ("p-wolf-pack", "Wolf Pack Alpha", "animal", "advanced", "winter", None, 5, 30, True, 0, "violet", "The leader of the wolf pack!"),
    # ===== PREMIUM FLOWERS (25) =====
    ("p-sakura", "Sakura Branch", "flower", "intermediate", "spring", None, 3, 15, True, 3, "pink", "A Japanese cherry blossom branch!"),
    ("p-water-lily", "Water Lily", "flower", "intermediate", "summer", None, 3, 15, True, 3, "pink", "A lily floating on a calm pond!"),
    ("p-magnolia", "Magnolia Bloom", "flower", "advanced", "spring", None, 4, 20, True, 3, "rose", "A big beautiful magnolia flower!"),
    ("p-jasmine", "Jasmine Flower", "flower", "beginner", "summer", None, 2, 10, True, 3, "yellow", "A sweet-smelling jasmine!"),
    ("p-violet", "Violet Flower", "flower", "beginner", "spring", None, 2, 8, True, 3, "purple", "A tiny purple violet!"),
    ("p-marigold", "Marigold", "flower", "intermediate", "fall", None, 3, 12, True, 3, "orange", "A bright orange marigold!"),
    ("p-forget-me-not", "Forget-Me-Not", "flower", "beginner", "spring", None, 2, 8, True, 3, "blue", "Tiny blue flowers that mean 'remember me'!"),
    ("p-birds-paradise", "Bird of Paradise", "flower", "advanced", "summer", None, 5, 25, True, 3, "orange", "An amazing tropical bird of paradise flower!"),
    ("p-calla-lily", "Calla Lily", "flower", "intermediate", "spring", None, 3, 15, True, 3, "violet", "An elegant calla lily with a curved petal!"),
    ("p-morning-glory", "Morning Glory", "flower", "intermediate", "summer", None, 3, 12, True, 3, "purple", "A trumpet-shaped morning glory!"),
    ("p-plumeria", "Plumeria", "flower", "intermediate", "summer", None, 3, 12, True, 3, "yellow", "A tropical plumeria - smells amazing!"),
    ("p-aster", "Star Aster", "flower", "beginner", "fall", None, 2, 10, True, 3, "purple", "A star-shaped aster flower!"),
    ("p-pansy", "Pansy Face", "flower", "beginner", "spring", None, 2, 8, True, 3, "fuchsia", "A pansy that looks like it has a face!"),
    ("p-camellia", "Camellia", "flower", "advanced", "winter", None, 4, 20, True, 3, "rose", "A perfect round camellia flower!"),
    ("p-bleeding-heart", "Bleeding Heart", "flower", "intermediate", "spring", "valentines", 3, 15, True, 3, "rose", "A heart-shaped flower that drips!"),
    ("p-protea", "Protea Flower", "flower", "advanced", "all", None, 5, 25, True, 3, "coral", "A spiky alien-looking protea!"),
    ("p-heliconia", "Heliconia", "flower", "advanced", "summer", None, 4, 20, True, 3, "red", "A wild tropical heliconia!"),
    ("p-wisteria", "Wisteria Vine", "flower", "advanced", "spring", None, 5, 25, True, 3, "purple", "Hanging purple wisteria flowers!"),
    ("p-zinnia", "Zinnia", "flower", "beginner", "summer", None, 2, 10, True, 3, "pink", "A round colorful zinnia!"),
    ("p-thistle", "Thistle", "flower", "intermediate", "fall", None, 3, 12, True, 3, "purple", "A spiky Scottish thistle!"),
    ("p-gardenia", "Gardenia", "flower", "intermediate", "summer", None, 3, 15, True, 3, "yellow", "A creamy white gardenia!"),
    ("p-snapdragon", "Snapdragon", "flower", "intermediate", "spring", None, 3, 12, True, 3, "red", "A flower that opens like a dragon's mouth!"),
    ("p-lollipop-flower", "Lollipop Flower", "flower", "beginner", "all", None, 1, 8, True, 3, "fuchsia", "A fun flower that looks like a lollipop!"),
    ("p-four-leaf-clover", "Lucky 4-Leaf Clover", "flower", "beginner", "spring", None, 2, 8, True, 2, "green", "Find the luck! A four-leaf clover!"),
    ("p-giant-sunflower", "Giant Sunflower", "flower", "advanced", "summer", None, 4, 20, True, 3, "yellow", "A sunflower as big as your head!"),
    # ===== PREMIUM OBJECTS (50) =====
    ("p-pirate-ship", "Pirate Ship", "object", "intermediate", "summer", None, 3, 15, True, 11, "amber", "Ahoy! A pirate ship with a skull flag!"),
    ("p-ufo", "Flying Saucer", "object", "intermediate", "all", None, 3, 12, True, 16, "teal", "A UFO from outer space!"),
    ("p-dragon-mask", "Dragon Mask", "object", "intermediate", "all", None, 3, 15, True, 0, "red", "A fierce dragon mask to wear!"),
    ("p-ninja-mask", "Ninja Mask", "object", "intermediate", "all", None, 3, 12, True, 0, "indigo", "A secret ninja mask!"),
    ("p-paper-phone", "Paper Phone", "object", "beginner", "all", None, 2, 8, True, 0, "sky", "A pretend phone made from paper!"),
    ("p-paper-watch", "Paper Watch", "object", "beginner", "all", None, 2, 8, True, 0, "amber", "A cool watch for your wrist!"),
    ("p-magic-box", "Magic Trick Box", "object", "intermediate", "all", None, 3, 15, True, 13, "purple", "A box that does magic tricks!"),
    ("p-paper-glasses", "Paper Glasses", "object", "beginner", "all", None, 1, 5, True, 0, "sky", "Silly glasses made from paper!"),
    ("p-paper-tie", "Paper Tie", "object", "beginner", "all", None, 2, 8, True, 0, "red", "A fancy tie for dress-up!"),
    ("p-space-rocket", "Space Rocket", "object", "intermediate", "all", None, 3, 15, True, 16, "orange", "Blast off to the moon!"),
    ("p-paper-boat-race", "Racing Boat", "object", "beginner", "summer", None, 2, 8, True, 11, "red", "The fastest paper boat ever!"),
    ("p-paper-car", "Race Car", "object", "intermediate", "all", None, 3, 12, True, 17, "red", "Zoom zoom! A speedy race car!"),
    ("p-paper-tank", "Paper Tank", "object", "advanced", "all", None, 4, 20, True, 0, "green", "A tough little paper tank!"),
    ("p-paper-helicopter", "Helicopter", "object", "intermediate", "all", None, 3, 12, True, 10, "sky", "A helicopter with spinning blades!"),
    ("p-paper-train", "Choo Choo Train", "object", "intermediate", "all", None, 3, 15, True, 0, "red", "All aboard the paper train!"),
    ("p-paper-dinosaur-egg", "Dino Egg", "object", "beginner", "all", None, 2, 8, True, 13, "green", "What's inside? A dinosaur egg!"),
    ("p-superhero-mask", "Superhero Mask", "object", "beginner", "all", None, 2, 8, True, 0, "red", "Be a superhero with this cool mask!"),
    ("p-paper-binoculars", "Binoculars", "object", "beginner", "all", None, 2, 10, True, 0, "green", "Spy on birds with paper binoculars!"),
    ("p-paper-telescope", "Telescope", "object", "intermediate", "all", None, 3, 12, True, 0, "indigo", "Look at the stars with a telescope!"),
    ("p-paper-medal", "Gold Medal", "object", "beginner", "all", None, 1, 5, True, 17, "yellow", "You're a winner! A gold medal!"),
    ("p-paper-badge", "Star Badge", "object", "beginner", "all", None, 1, 5, True, 5, "yellow", "A sheriff's star badge!"),
    ("p-paper-tiara", "Princess Tiara", "object", "beginner", "all", None, 2, 10, True, 12, "fuchsia", "A sparkly princess tiara crown!"),
    ("p-snowman", "Paper Snowman", "object", "beginner", "winter", "christmas", 2, 10, True, 8, "sky", "A happy snowman with a carrot nose!"),
    ("p-reindeer", "Reindeer", "object", "intermediate", "winter", "christmas", 3, 12, True, 0, "amber", "Rudolph the red-nosed reindeer!"),
    ("p-gingerbread", "Gingerbread Man", "object", "beginner", "winter", "christmas", 2, 8, True, 0, "amber", "Run run as fast as you can!"),
    ("p-stocking", "Christmas Stocking", "object", "beginner", "winter", "christmas", 2, 8, True, 0, "red", "Hang it up for Santa to fill!"),
    ("p-easter-bunny", "Easter Bunny Box", "object", "intermediate", "spring", "easter", 3, 15, True, 0, "pink", "A bunny that holds Easter candy!"),
    ("p-turkey", "Thanksgiving Turkey", "object", "intermediate", "fall", None, 3, 12, True, 0, "orange", "Gobble gobble! A turkey!"),
    ("p-shamrock", "Lucky Shamrock", "object", "beginner", "spring", None, 2, 8, True, 2, "green", "A lucky Irish shamrock!"),
    ("p-candy-box", "Candy Box", "object", "intermediate", "all", None, 3, 12, True, 13, "rose", "A cute box for candy and treats!"),
    ("p-paper-flower-pot", "Flower Pot", "object", "intermediate", "spring", None, 3, 12, True, 0, "coral", "A pot to put your paper flowers in!"),
    ("p-paper-frame", "Picture Frame", "object", "intermediate", "all", None, 3, 12, True, 0, "amber", "Frame your favorite photo!"),
    ("p-paper-tree", "3D Christmas Tree", "object", "intermediate", "winter", "christmas", 3, 15, True, 2, "green", "A tree that stands up on its own!"),
    ("p-paper-wreath", "Door Wreath", "object", "intermediate", "winter", "christmas", 3, 15, True, 2, "green", "Hang it on your door for the holidays!"),
    ("p-paper-angel2", "Angel Ornament", "object", "intermediate", "winter", "christmas", 3, 12, True, 0, "yellow", "A beautiful angel for the tree!"),
    ("p-heart-box", "Heart Gift Box", "object", "intermediate", "all", "valentines", 3, 15, True, 4, "rose", "A heart-shaped box for a special gift!"),
    ("p-love-bird", "Love Birds", "object", "intermediate", "all", "valentines", 3, 15, True, 0, "rose", "Two birds sitting together in love!"),
    ("p-cupid-arrow", "Cupid's Arrow", "object", "beginner", "all", "valentines", 2, 8, True, 0, "rose", "An arrow of love!"),
    ("p-valentine-card", "Pop-Up Valentine", "object", "intermediate", "all", "valentines", 3, 15, True, 4, "red", "A card with a pop-up heart inside!"),
    ("p-paper-spider", "Hanging Spider", "object", "beginner", "fall", "halloween", 2, 8, True, 0, "indigo", "A creepy spider on a web!"),
    ("p-paper-vampire", "Vampire Teeth", "object", "beginner", "fall", "halloween", 2, 8, True, 0, "red", "Scary vampire teeth to wear!"),
    ("p-haunted-house", "Haunted House", "object", "advanced", "fall", "halloween", 4, 25, True, 14, "purple", "A spooky haunted house!"),
    ("p-skeleton-hand", "Skeleton Hand", "object", "intermediate", "fall", "halloween", 3, 12, True, 0, "violet", "A bony skeleton hand!"),
    ("p-mummy", "Mummy Wrap", "object", "beginner", "fall", "halloween", 2, 8, True, 0, "yellow", "A wrapped-up mummy!"),
    ("p-paper-ice-cream", "Ice Cream Sundae", "object", "beginner", "summer", None, 2, 10, True, 29, "coral", "A yummy ice cream sundae!"),
    ("p-paper-pizza", "Pizza Slice", "object", "beginner", "all", None, 2, 8, True, 28, "orange", "A delicious pizza slice!"),
    ("p-paper-cupcake", "Birthday Cupcake", "object", "beginner", "all", None, 2, 10, True, 0, "pink", "A cupcake for a birthday party!"),
    ("p-paper-donut", "Sprinkle Donut", "object", "beginner", "all", None, 2, 8, True, 0, "coral", "A donut with rainbow sprinkles!"),
    ("p-paper-lollipop", "Lollipop", "object", "beginner", "all", None, 1, 5, True, 0, "fuchsia", "A swirly lollipop on a stick!"),
    ("p-paper-watermelon", "Watermelon Slice", "object", "beginner", "summer", None, 2, 8, True, 0, "green", "A juicy watermelon slice!"),
]

def generate_all_projects():
    projects = []
    colors = list(C.values())
    for r in RAW:
        proj_id, title, cat, skill, season, holiday, diff, time_min, premium, icon_idx, color_key, desc = r
        steps = get_steps(cat, skill, title)
        age = "5-7" if skill == "beginner" else "8-10" if skill == "intermediate" else "11+"
        projects.append({
            "id": proj_id,
            "title": title,
            "description": desc,
            "skill_level": skill,
            "age_range": age,
            "season": season,
            "holiday": holiday,
            "difficulty_rating": diff,
            "estimated_time": f"{time_min} min",
            "is_premium": premium,
            "has_video": False,
            "icon_name": ICONS[icon_idx % len(ICONS)],
            "color": C.get(color_key, "#38BDF8"),
            "xp_reward": 10 if skill == "beginner" else 25 if skill == "intermediate" else 50,
            "steps": steps,
        })
    return projects
